/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paint.view;

import Paint.controller.Controller;
import Paint.model.Shape;
import Paint.view.MyCanvas;
import java.awt.Color;
import java.awt.Point;
import java.io.File;
import javax.swing.*;

/**
 *
 * @author omar_
 */
public class view extends javax.swing.JFrame {

    Controller control = new Controller();
    Shape element;
    Color c ;
    Point position1 = new Point(0, 0);
    Point position2 = new Point(0, 0);
    int flag=0,test=0;
    boolean filled;
    Point ps = new Point();
    MyCanvas cs = new MyCanvas();
  JFrame Frame = new JFrame();
   JFileChooser chooser=new JFileChooser();
       JColorChooser jcc = new JColorChooser();
    public view() {
        initComponents();
        control.setCanvas((MyCanvas) jPanel1);
       c=Color.BLUE;
      filled=fill.isSelected();
        setLocation(250, 75);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        shape = new javax.swing.JComboBox();
        color = new java.awt.Button();
        move = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        undo = new javax.swing.JButton();
        redo = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        resize = new javax.swing.JButton();
        copy = new javax.swing.JButton();
        savejason = new javax.swing.JButton();
        savexml = new javax.swing.JButton();
        load = new javax.swing.JButton();
        fill = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new Paint.view.MyCanvas();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(0, 153, 153));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153)));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        shape.setBackground(new java.awt.Color(153, 255, 255));
        shape.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "Line", "Elliptical", "Circle", "Square", "Rectangle", "Triangle" }));
        shape.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shapeActionPerformed(evt);
            }
        });
        jPanel3.add(shape, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 90, -1));

        color.setBackground(new java.awt.Color(0, 0, 153));
        color.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colorActionPerformed(evt);
            }
        });
        jPanel3.add(color, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, 20, 20));

        move.setIcon(new javax.swing.ImageIcon(getClass().getResource("/paint/view/Webp.net-resizeimage (13).png"))); // NOI18N
        move.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moveActionPerformed(evt);
            }
        });
        jPanel3.add(move, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 40, 30));

        clear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/paint/view/Webp.net-resizeimage (15).png"))); // NOI18N
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        jPanel3.add(clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 40, 30));

        undo.setBackground(new java.awt.Color(255, 255, 255));
        undo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/paint/view/Webp.net-resizeimage2.jpg"))); // NOI18N
        undo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        undo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                undoActionPerformed(evt);
            }
        });
        jPanel3.add(undo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 40, 40));

        redo.setBackground(new java.awt.Color(255, 255, 255));
        redo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/paint/view/Webp.net-resizeimage.jpg"))); // NOI18N
        redo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        redo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                redoActionPerformed(evt);
            }
        });
        jPanel3.add(redo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 40, 40));

        delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/paint/view/Webp.net-resizeimage (14).png"))); // NOI18N
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        jPanel3.add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 40, 30));

        resize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/paint/view/Webp.net-resizeimage (4).png"))); // NOI18N
        resize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resizeActionPerformed(evt);
            }
        });
        jPanel3.add(resize, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 40, 30));

        copy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/paint/view/Webp.net-resizeimage (2).png"))); // NOI18N
        copy.setToolTipText("");
        copy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                copyActionPerformed(evt);
            }
        });
        jPanel3.add(copy, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 40, 30));

        savejason.setIcon(new javax.swing.ImageIcon(getClass().getResource("/paint/view/Webp.net-resizeimage (10).png"))); // NOI18N
        savejason.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savejasonActionPerformed(evt);
            }
        });
        jPanel3.add(savejason, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 50, -1));

        savexml.setIcon(new javax.swing.ImageIcon(getClass().getResource("/paint/view/Webp.net-resizeimage (11).png"))); // NOI18N
        savexml.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savexmlActionPerformed(evt);
            }
        });
        jPanel3.add(savexml, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 50, -1));

        load.setIcon(new javax.swing.ImageIcon(getClass().getResource("/paint/view/Webp.net-resizeimage (16).png"))); // NOI18N
        load.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadActionPerformed(evt);
            }
        });
        jPanel3.add(load, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 50, 30));

        fill.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        fill.setText("Fill");
        fill.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        fill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fillActionPerformed(evt);
            }
        });
        jPanel3.add(fill, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, -1, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/paint/view/if_Brush_728914.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 240, 230));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/paint/view/dripping-blue-paint-on-a-white-wood-background_1048-6143.jpg"))); // NOI18N
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 540));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 540));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(51, 51, 51));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jPanel1MouseReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 570, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 540, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 570, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseReleased
      

      try{  if(test==0){
            element.setPosition2(evt.getPoint());
            element.setColor(c);  
            repaint();
           control.refresh(jPanel1);
      }
      }catch(Exception e){
      
      JOptionPane.showMessageDialog(null,"Please choose a shape to draw !!");
      }
    }//GEN-LAST:event_jPanel1MouseReleased

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed

       try{
        if (test == 0) {
           element = control.factory(shape.getSelectedItem().toString().toLowerCase());
            element.setPosition(evt.getPoint());
          element.Filled(filled);
            control.addShape(element);
            element.setColor(c);
               }else if(flag==0 )
                {
              ps = evt.getPoint();  
                }
        else if (flag == 3) {
            int selected = control.Select(ps);
            Point pm = evt.getPoint();
            Shape s = control.getShape(selected);
            
            control.delete(selected);
            s.Filled(s.isFilled());
            control.move(s,pm).setColor(s.getColor());
            
            control.addShape(control.move(s,pm));
            control.refresh(jPanel1);
            repaint();
            flag=0;
            jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
        } else if (flag == 4) {
            int selected = control.Select(ps);
            Point pz = evt.getPoint();
            Shape s = control.getShape(selected);
          
            control.delete(selected);
            
            control.move(s,pz).setColor(s.getColor());
           s.Filled(s.isFilled());
            control.addShape(control.resize(s,pz,control.getCenter(s)));
            control.refresh(jPanel1);
            repaint();
            flag=0;
            jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
        } else if (flag == 5) {
            int selected = control.Select(ps);
            Point pm = evt.getPoint();
            Shape s = control.getShape(selected);
            control.move(s,pm).setColor(s.getColor());
         s.Filled(s.isFilled());
            control.addShape(control.move(s,pm));
            control.refresh(jPanel1);
            repaint();
            flag=0;
            jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
        }else {
        
        }
       }catch(Exception e){
    }
    }//GEN-LAST:event_jPanel1MousePressed

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
try{
   if ( test==0) {
            element.setPosition2(evt.getPoint());
            repaint();
            //control.refresh(jPanel1);
            
       }
}catch(Exception e){}

    }//GEN-LAST:event_jPanel1MouseDragged

    private void colorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colorActionPerformed
        // TODO add your handling code here:
       // JColorChooser jcc = new JColorChooser();
      c=  JColorChooser.showDialog(null,"Please Select a color",Color.BLUE);
        color.setBackground(c);
    }//GEN-LAST:event_colorActionPerformed

    private void undoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_undoActionPerformed
        // TODO add your handling code here:
        control.undo();
        repaint();
    }//GEN-LAST:event_undoActionPerformed

    private void redoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_redoActionPerformed
        // TODO add your handling code here:
        control.redo();
        repaint();
    }//GEN-LAST:event_redoActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        // TODO add your handling code here:
        control.cleardall();
        repaint();

    }//GEN-LAST:event_clearActionPerformed

    private void resizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resizeActionPerformed
        // TODO add your handling code here:
        int selected = control.Select(ps);  
        if (selected == -1) {
            JOptionPane.showMessageDialog(null, "Please select a shape first.");
        } else {
            flag = 4;
            jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.NE_RESIZE_CURSOR));
        }
    }//GEN-LAST:event_resizeActionPerformed

    private void moveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moveActionPerformed
        // TODO add your handling code here:
        int selected = control.Select(ps);
        if (selected == -1) {
            JOptionPane.showMessageDialog(null, "Please select a shape first.");
        } else {
            flag = 3;
            jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));
        }
    }//GEN-LAST:event_moveActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
        int selected = control.Select(ps);
        if (selected == -1) {
            JOptionPane.showMessageDialog(null, "Please select a shape first.");
        } else {
            control.delete(selected);
            control.refresh(jPanel1);
            repaint();
        }
  
    }//GEN-LAST:event_deleteActionPerformed

    private void shapeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shapeActionPerformed
        // TODO add your handling code here:
      
        test=0;
    }//GEN-LAST:event_shapeActionPerformed

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
        // TODO add your handling code here:
        test=1;
    }//GEN-LAST:event_jPanel1MouseClicked

    private void copyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_copyActionPerformed
        // TODO add your handling code here:
          int selected = control.Select(ps);
        if (selected == -1) {
            JOptionPane.showMessageDialog(null, "Please select a shape first.");
        } else {
            flag = 5;
        }
   
    }//GEN-LAST:event_copyActionPerformed

    private void savejasonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savejasonActionPerformed
        // TODO add your handling code here:
     //    JFrame Frame = new JFrame();
     //   JFileChooser chooser=new JFileChooser();
        chooser.setDialogTitle("Specify a file to save"); 
        int userSelection = chooser.showSaveDialog(Frame);
        if (userSelection == JFileChooser.APPROVE_OPTION) {
        File fileToSave = chooser.getSelectedFile();
        System.out.println("Save as file: " + fileToSave.getAbsolutePath());
        control.save(fileToSave.getAbsolutePath()+".json");}
    }//GEN-LAST:event_savejasonActionPerformed

    private void loadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadActionPerformed
        // TODO add your handling code here:
       //  JFileChooser chooser=new JFileChooser();
        chooser.setDialogTitle("Specify a file to open"); 
        int userSelection = chooser.showOpenDialog(null);
        if (userSelection == JFileChooser.APPROVE_OPTION) {
        File fileToOpen = chooser.getSelectedFile();
        System.out.println("Save as file: " + fileToOpen.getPath());
        control.load(fileToOpen.getPath());}
        control.refresh(jPanel1);
        repaint();
               
    }//GEN-LAST:event_loadActionPerformed

    private void savexmlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savexmlActionPerformed
//         JFrame Frame = new JFrame();
      //  JFileChooser chooser=new JFileChooser();
        chooser.setDialogTitle("Specify a file to save"); 
        int userSelection = chooser.showSaveDialog(Frame);
        if (userSelection == JFileChooser.APPROVE_OPTION) {
        File fileToSave = chooser.getSelectedFile();
        System.out.println("Save as file: " + fileToSave.getAbsolutePath());
        control.save(fileToSave.getAbsolutePath()+".xml");
        }
    }//GEN-LAST:event_savexmlActionPerformed

    private void fillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fillActionPerformed
        // TODO add your handling code here:
    try{ filled=fill.isSelected();
    //element.Filled(filled);
    }catch(Exception e)
    {}
    }//GEN-LAST:event_fillActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new view().setVisible(false);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clear;
    private java.awt.Button color;
    private javax.swing.JButton copy;
    private javax.swing.JButton delete;
    private javax.swing.JCheckBox fill;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton load;
    private javax.swing.JButton move;
    private javax.swing.JButton redo;
    private javax.swing.JButton resize;
    private javax.swing.JButton savejason;
    private javax.swing.JButton savexml;
    private javax.swing.JComboBox shape;
    private javax.swing.JButton undo;
    // End of variables declaration//GEN-END:variables

    public javax.swing.JPanel getjPanel1() {
        return jPanel1;
    }
}
